version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "ts-loader"
        update-types: ["version-update:semver-major"]
